drf-test/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"groups", views.GroupViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

drf-test/drftest/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('snippets/', include('snippets.urls'))
]


urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

module_19/authors/urls.py
from django.urls import path
from . import views

app_name = 'authors'
urlpatterns = [
    path('register/', views.register_user, name='register_author'),
    path('login/', views.UserLoginView.as_view(), name='login_author'),
    path('logout/', views.LogoutView.as_view(), name='logout_author'),
    path('profile/', views.profile, name='profile'),
    path('password/', views.change_password, name='password'),
    path('my_post/', views.authors_posts, name='posts')
]

module_19/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('add/', views.AddPostCreateView.as_view(), name='add'),
    path('edit/<int:id>/', views.EditPostView.as_view(), name='edit'),
    path('delete/<int:id>/', views.DeletePostView.as_view(), name='delete'),
    path('detail/<int:id>/', views.PostDetailView.as_view(), name='detail')
]

smartnotes/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("home", views.HomeView.as_view(), name="home"),
    path("login", views.LoginInterfaceView.as_view(), name="login"),
    path("logout", views.LogoutInterfaceView.as_view(), name="logout"),
    path("signup", views.SignupView.as_view(), name="signup")
]

module_19/post/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Category(models.Model):
    name = models.CharField(
        max_length=150,
    )
    slug = models.SlugField()


class Post(models.Model):
    title = models.CharField(
        max_length=150
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    content = models.TextField()
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )

module_19/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(
        max_length=100,
    )
    slug = models.SlugField(
        max_length=100,
        null=True,
        blank=True,
        unique=True,
        
    )

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(
        max_length=150
    )
    content = models.TextField()
    category = models.ManyToManyField(Category)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='posts/media/uploads/', blank=True, null=True)
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=150)
    email = models.EmailField(unique=True)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'comment by {self.name}'

module_19/authors/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class AuthorRegistrationForm(UserCreationForm):

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    class Meta():
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email'
        ]

class ChangeUserDataForm(UserChangeForm):
    password = None

    class Meta():
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email'
        ]

module_19/posts/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta():
        model = Post
        exclude = ['author']


class CommentForm(ModelForm):
    class Meta:
        model = Comment 
        fields = ['name', 'email', 'body']

module_19/BlogProject/views.py
from django.shortcuts import render
from posts.models import Post, Category

def home(request, cat = None):
    all_post = Post.objects.all()
    if cat is not None:
        category = Category.objects.get(slug=cat)
        all_post = Post.objects.filter(category=category)
    return render(request, 'home.html', {
        'posts': all_post
    })

module_19/authors/views.py
from django.shortcuts import render, redirect
from .forms import AuthorRegistrationForm, ChangeUserDataForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from posts.models import Post


from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
# Create your views here.

def register_user(request):
    if request.method == 'POST':
        registration_form = AuthorRegistrationForm(request.POST)
        if registration_form.is_valid():
            registration_form.save()
            messages.success(request, 'Account Created Successfully')
            return redirect('home')
    else:
        registration_form = AuthorRegistrationForm()

    return render(request, 'authors/author_forms.html', {
        'form': registration_form,
        'title': 'Author Registration'
    })

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user_name = form.cleaned_data['username']
            user_pass = form.cleaned_data['password']
            user = authenticate(username=user_name, password=user_pass)
            if user is not None:
                login(request, user)
                # messages.success(request, 'Logged In Successfully')
                return redirect('home')
    else:
        form = AuthenticationForm()
    
    return render(request, 'authors/author_forms.html', {
        'form': form,
        'title': 'Author Login'
    })

class UserLoginView(LoginView):
    template_name = 'authors/author_forms.html'
    success_url = reverse_lazy('profile')
    def form_valid(self, form):
        messages.success(self.request, 'Logged in Successful')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.success(self.request, 'Logged in Unsuccessful')
        return super().form_invalid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Author Login'
        return context
    
    def get_success_url(self) -> str:
        return reverse_lazy('home')

# @login_required
# def logout_user(request):
#     logout(request)
#     return redirect('authors:login_author')


@login_required
def profile(request):
    if request.method == 'POST':
        profile_form = ChangeUserDataForm(request.POST, instance=request.user)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile Updated Successfully')
            return redirect('home')
    else:
        profile_form = ChangeUserDataForm(instance=request.user)
    return render(request, 'authors/author_forms.html', {
        'form': profile_form,
        'title': 'User Profile',
    })

@login_required
def change_password(request):
    if request.method == 'POST':
        password_form = PasswordChangeForm(request.POST, request.user)
        if password_form.is_valid():
            password_form.save()
            messages.success(request, 'Password Updated Successfully')
            update_session_auth_hash(request, password_form.user)
            return redirect('authors:profile')
    else:
        password_form = PasswordChangeForm(request.user)

    return render(request, 'authors/author_forms.html', {
        'form': password_form,
        'title': 'Change Password'
    })

@login_required
def authors_posts(request):
    all_post = Post.objects.filter(author=request.user)
    return render(request, 'authors/all_post.html', {
        'posts': all_post,
        'title': 'My Posts'
    })

module_19/posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, CommentForm
from .models import Post
from django.contrib.auth.decorators import login_required

from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
# Create your views here.

# @login_required
# def add_post(request):
#     if request.method == 'POST':
#         post_form = PostForm(request.POST)
#         if post_form.is_valid():
#             post_form.instance.author = request.user
#             post_form.save()
#             return redirect('authors:posts')
#     else:
#         post_form = PostForm()
    
#     return render(request, 'posts/post_form.html', {
#         'form': post_form,
#         'title': 'Add Post'
#     })

# add post using class based view
@method_decorator(login_required, name='dispatch')
class AddPostCreateView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('authors:posts')
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

# @login_required
# def edit_post(request, id):
#     post = Post.objects.get(pk=id)
#     post_form = PostForm(instance=post)
#     if request.method == 'POST':
#         post_form = PostForm(request.POST, instance=post)
#         if post_form.is_valid():
#             post_form.save()
#             return redirect('authors:posts')
#     return render(request, 'posts/post_form.html', {
#         'form': post_form,
#         'title': 'Edit Post'
#     })

@method_decorator(login_required, name='dispatch')
class EditPostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/post_form.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('authors:posts')

# @login_required
# def delete_post(request, id):
#     post = Post.objects.get(pk=id)
#     post.delete()
#     return redirect('authors:posts')

@method_decorator(login_required, name='dispatch')
class DeletePostView(DeleteView):
    model = Post
    template_name = 'posts/post_confirm_delete.html'
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('authors:posts')

class PostDetailView(DetailView):
    model = Post
    pk_url_kwarg = 'id'
    template_name = 'posts/post_detail.html'

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(data=self.request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = self.get_object() 
            
            comment.save()

        return self.get(request, *args, **kwargs)

        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = 'test_comments'

        context['comments'] = self.get_object().comments.all()
        context['comment_form'] = CommentForm()
        return context
    

smartnotes/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from datetime import datetime
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect

class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = "home/signup.html"
    success_url = "smart/notes"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("smart/notes")
        return super().get(self, request, *args, **kwargs)

class HomeView(TemplateView):
    template_name = 'home/welcome.html'
    extra_context = {"today": datetime.now()}

class LoginInterfaceView(LoginView):
    template_name = "home/login.html"

class LogoutInterfaceView(LogoutView):
    template_name = "home/logout.html"


# class AuthorizedView(LoginRequiredMixin, TemplateView):
#     template_name = "home/authorized.html"
#     login_url = "/admin"

module_19/templates/home.html
{% extends 'layout.html' %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="row row-cols-1 row-cols-md-2 g-4 mx-auto" style="width: 50%;">
    {% for post in posts %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <img src="{{ post.image.url }}" alt="" style="width: 100%;">
                <h5 class="card-title"><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></h5>
                <p class="card-text">{{ post.author }}</p>
                {% for category in post.category.all %}
                <a href="{% url 'bycategory' category.slug %}" class="link-primary mt-1">{{ category }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}

module_19/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <nav class="nav justify-content-center m-3">
        {% if request.user.is_authenticated %}
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">BlogProject</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'authors:profile' %}">Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'authors:posts' %}">My Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'posts:add' %}">New Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'authors:password' %}">Password</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'authors:logout_author' %}">Logout</a>
            </li>
        </ul>
        {% else %}
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">BlogProject</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'authors:register_author' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'authors:login_author' %}">Login</a>
            </li>
        </ul>
        {% endif %}
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="mx-auto alert alert-secondary " role="alert" style="width: 50%;">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div>
        {% block content %}
            
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>

</html>